#!/bin/bash
#
# by Ian Katz
# generates undabite as seen in sbemail70 with terminal colors 
# (not perfect color-wise, due to limitations of console colors)


echo ""

echo -e "\e[0m \e[47m                         \e[0m "
echo -e " \e[47m \e[0m                       \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m                     \e[0m \e[47m \e[0m "

echo -e " \e[47m \e[0m \e[47m \e[0m    \e[47m \e[0m              \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m   \e[47m \e[0m               \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m  \e[47m \e[0m \e[47m \e[0m \e[44m    \e[0m  \e[41m  \e[0m     \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m     \e[44m      \e[41m   \e[0m     \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[44m    \e[47;30;1m   █\e[41m \e[0m      \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[44m  \e[47m  \e[0m \e[47m \e[0m \e[47;30;1m █\e[0m      \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[47;30;1m█       █\e[0m \e[47;30;1m██\e[0m   \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[47;30;1m█    █████ █\e[0m   \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[47;30;1m█         █\e[0m    \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[47;30;1m█         █\e[0m    \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[47;30;1m█        █\e[0m     \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[47;30;1m█████████\e[0m      \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m         \e[0m      \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m      \e[47m \e[41m  \e[0m      \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m     \e[47m   \e[41m  \e[0m     \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m   \e[47m       \e[0m     \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m    \e[47m     \e[41m \e[0m     \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m     \e[47m   \e[41m   \e[0m    \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m    \e[47m \e[41m   \e[47m \e[41m  \e[0m    \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m           \e[0m    \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m           \e[0m    \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m    \e[41m      \e[47;30;1m █\e[0m       \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m \e[0m       \e[47;30;1m█ █ █\e[0m       \e[47m \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m \e[47m                     \e[0m \e[47m \e[0m "
echo -e " \e[47m \e[0m                       \e[47m \e[0m "
echo -e "\e[0m \e[47m                         \e[0m "

echo ""

