# .bash_profile

# Set bash-specific features
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:$HOME/ifreecarve-posix-bin
#USERNAME="Ian Katz"
#PS1="\e[31m\@\e[0m-\e[32m\u@\e[32;1m\h\e[0m\n\e[36m\w>\e[0m"
FAIL="\`if [ \$? = 0 ]; then echo ; else echo \[\e[31m\]FAIL\[\e[0m\] && echo -e '\n'; fi \`"
PS1="$FAIL\[\e[32m\u@\e[33;1m\H\e[0m:\e[36m\w\e[0m\]\n\[\e[36m\]\j \\$ \[\e[0m\]"
#          host color --^

export PATH PS1


